# Site settings
title: emijayne
email: emijayne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  my partial portfolio - web development and production art
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://emijayne.github.io" # the base hostname & protocol for your site
twitter_username: emijayne
github_username: emijayne
drupal_username: emijayne

# Build settings
markdown: kramdown
