# Site settings
title: emijayne | just a snippet
email: emijayne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  emily is a web developer and production professional who loves learning new things
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://emijayne.com" # the base hostname & protocol for your site
twitter_username: emijayne
github_username: emijayne
drupal_username: emijayne

# Build settings
markdown: kramdown
